### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by fommil** [ancane/scala-outline-popup#6]
When I try to use `scala-outline-popup` I get

```
scala-outline-popup: Symbol's function definition is void: artist-move-to-xy [2 times]
```

are you forgetting to declare a dependency on melpa?

**Comment by ancane** [comment]
Sorry, for that. Forgot to require artist.
PS. Lately, for whatever reason, when I open the popup at the beginning of the line, I get artifacts in the popup: it shrinks to 1/2 chars wide. Did you happen to see anything like that?

**Comment by fommil** [comment]
Hmm. I'll look at that when you update with the deps and let you know.

**Comment by ancane** [comment]
scala-outline-popup 20150518.1149 from melpa should be good.
