### ISSUE TITLE
generalise to imenu

### ISSUE THREAD

**Issue by fommil** [ancane/scala-outline-popup#7]
I've been learning more about `imenu` recently and it occurred to me that this popup would be really useful to every emacs user if it were a general `imenu` popup rather than just for `scala-mode`.

If the detectors in this project are better than the `imenu` detectors in `scala-mode` then perhaps they could be submitted as a PR improvement there and everybody benefits?

That means the best way to implement an ENSIME backed file navigation is by simply populating the `imenu`.

**Comment by ancane** [comment]
I'll take a look at `scala-mode` imenu regexes. Most probably, those are far better than mine.

**Comment by fommil** [comment]
but what about refactoring this to be a general `popup-imenu`? It would be incredibly useful in other modes. I find myself missing it.

**Comment by ancane** [comment]
Oh, popup-imenu. Now I see the idea. Thanks!
